In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import datetime as dt

In [35]:
def wrangle(nifty_50_stocks):
    # get nifty stocks
    df = pd.read_csv(nifty_50_stocks)
    # cponvert symbol to accessible for yahoo finance api
    df.Symbol = df.Symbol.apply(lambda x: x+'.NS')

    # start and end date
    start = dt.date.today() - dt.timedelta(days=365*10)
    end = dt.date.today() - dt.timedelta(days=1)

    # extract price data and convert to log returns
    df_prices = yf.download(list(df.Symbol), start=start, end=end, interval='1d')['Adj Close']
    # annualized return
    df_return = ((np.log(df_prices)-np.log(df_prices.shift(1)))*252).dropna()

    
    return df_return

In [36]:
nifty_50_stocks = 'ind_nifty50list.csv'
data = wrangle(nifty_50_stocks)
data

[*********************100%%**********************]  50 of 50 completed

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TRENT.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2017-11-20,6.041920,-1.481337,1.132211,-1.067209,1.274458,2.747124,2.142568,2.511223,1.476398,-0.434394,...,0.024356,14.139791,0.715913,0.341196,-0.358638,-4.063134,-0.754234,-3.945378,-5.115751,-0.683944
2017-11-21,-11.162552,1.387040,11.210053,-1.310596,0.761547,4.487566,1.585366,0.627376,-3.245311,5.364578,...,9.983883,-1.609349,0.743599,3.280405,-2.859185,8.853945,9.927509,17.493262,-1.081144,-0.299835
2017-11-22,7.044301,8.469854,9.311709,3.022391,-2.920267,0.986908,-1.449019,-5.034975,4.085116,-2.086720,...,-1.314856,0.828947,2.570701,-0.106297,0.724907,-5.807038,-0.711786,2.869006,4.023087,0.257016
2017-11-23,-8.609295,-4.539565,-2.190781,-3.174400,1.696028,-3.720043,-2.089834,-1.467454,9.259391,-1.392308,...,4.433408,0.688722,-1.385521,0.584098,0.056398,3.628991,-2.256912,3.787279,-2.710012,-0.643040
2017-11-24,1.236307,-1.552326,1.246304,0.000000,0.624417,1.819002,1.321912,3.737207,-3.321642,0.228358,...,2.187854,3.551284,-0.443787,-1.507260,0.638358,2.305560,7.212833,-1.537430,3.358418,-0.730749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-28,9.655189,6.321796,-0.674014,3.708289,-3.789224,-4.857573,3.379245,0.043765,-2.137198,-0.401163,...,5.692055,0.737022,4.092250,6.009234,2.059707,-2.049011,1.269699,-1.841572,2.222477,6.928962
2024-10-29,4.458020,3.791770,2.215075,-0.756669,3.258966,-4.070242,5.224441,4.020478,12.381763,-4.008629,...,-4.179517,4.136164,-10.455140,1.144526,-0.962817,-0.600182,0.026853,3.508286,0.442609,1.618866
2024-10-30,10.457640,4.277614,-0.178590,0.319743,-3.517196,2.286835,-2.040845,-2.433931,4.316074,-0.577902,...,-2.639335,7.667852,-0.763656,-1.837142,0.580590,-2.018434,1.915287,-5.425945,2.100276,1.363429
2024-10-31,-1.878337,-3.681685,1.446674,-5.182658,-2.347015,-2.659317,-0.244569,-2.375358,-3.207990,-3.221905,...,-0.435768,-5.014664,-1.851352,-0.694525,-7.272832,-9.424378,-3.173268,-4.349410,-3.155858,-6.068783
2024-11-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [37]:
data.mean()

Ticker
ADANIENT.NS      0.522208
ADANIPORTS.NS    0.187052
APOLLOHOSP.NS    0.281576
ASIANPAINT.NS    0.142496
AXISBANK.NS      0.112332
BAJAJ-AUTO.NS    0.193190
BAJAJFINSV.NS    0.180599
BAJFINANCE.NS    0.201007
BEL.NS           0.251238
BHARTIARTL.NS    0.194835
BPCL.NS          0.099319
BRITANNIA.NS     0.145230
CIPLA.NS         0.144477
COALINDIA.NS     0.160616
DRREDDY.NS       0.174564
EICHERMOT.NS     0.088013
GRASIM.NS        0.127663
HCLTECH.NS       0.237772
HDFCBANK.NS      0.102489
HDFCLIFE.NS      0.111178
HEROMOTOCO.NS    0.077985
HINDALCO.NS      0.149716
HINDUNILVR.NS    0.114358
ICICIBANK.NS     0.209717
INDUSINDBK.NS   -0.056898
INFY.NS          0.216148
ITC.NS           0.128842
JSWSTEEL.NS      0.204643
KOTAKBANK.NS     0.077770
LT.NS            0.175583
M&M.NS           0.209036
MARUTI.NS        0.052087
NESTLEIND.NS     0.173293
NTPC.NS          0.200061
ONGC.NS          0.114089
POWERGRID.NS     0.199268
RELIANCE.NS      0.177031
SBILIFE.NS       0.134299
SBIN.NS          0.139214
SHRIRAMFIN.NS    0.147149
SUNPHARMA.NS     0.195939
TATACONSUM.NS    0.206741
TATAMOTORS.NS    0.100970
TATASTEEL.NS     0.257317
TCS.NS           0.175451
TECHM.NS         0.205898
TITAN.NS         0.214463
TRENT.NS         0.457932
ULTRACEMCO.NS    0.144183
WIPRO.NS         0.137998
dtype: float64